### ISSUE TITLE
feature-1-data-by-year

### ISSUE THREAD

**Issue by Victor-Park** [Victor-Park/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can retrieve data for a single year in Formula 1

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In mobile screen, user can click the menu button to show list of years. In desktop screen, list of years is displayed by default. Selecting a year will send a request for Formula 1 data for that year.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="1174" alt="Screen Shot 2022-04-21 at 2 39 02 PM" src="https://user-images.githubusercontent.com/99834589/164556456-7c02288e-1cce-425e-b24f-afef0057db02.png">
<img width="605" alt="Screen Shot 2022-04-20 at 2 40 23 PM" src="https://user-images.githubusercontent.com/99834589/164327527-49b28a62-cb1d-487a-88eb-f3c0ca4aedf6.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Write HTML and CSS for the foundation
- [x] Add left column containing list of years found in F1 API
- [x] Make the list of years scrollable up and down within its container
- [x] Listen for 'click' event on the year buttons and:
  - [x] Change the color of the button red
  - [x] Send request to get data for the selected year
- [x] Add a hamburger menu button on the top left corner of the page that:
  - [x] Listens for 'click' event and:
    - [x] Displays if hidden
    - [x] Hides if displayed
    - [x] Pushes content right
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
