### ISSUE TITLE
feature-2-race-data

### ISSUE THREAD

**Issue by Victor-Park** [Victor-Park/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click on "Races" tab to see list of past and upcoming races.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Under the "Races" tab, user will be able to view data for past and upcoming races for each year. Selecting certain year will display data from the corresponding year.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="1175" alt="Screen Shot 2022-04-20 at 2 45 34 PM" src="https://user-images.githubusercontent.com/99834589/164328177-acb5736e-a538-4461-b6d8-e3fc1d7cca5a.png">
<img width="815" alt="Screen Shot 2022-04-20 at 2 44 53 PM" src="https://user-images.githubusercontent.com/99834589/164328081-c78caddc-1b3f-4564-98ff-5f896873a584.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a tab named "Races" that is 1/3 width of the page, with green background and white font
- [x] Create header for data table indicating which year/season is selected
- [x] Send request to get data (Round #, Grand Prix Name, Date, Time, Circuit) by year
- [x] Display data in a table format
- [x] Modify the year button event listener so that clicking on a different year loads data from that year into the table
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
