### ISSUE TITLE
feature-3-driver-standings

### ISSUE THREAD

**Issue by Victor-Park** [Victor-Park/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click on "Driver Standings" tab to see list of drivers and standings

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user clicks "Driver Standings" tab, data such as driver name, position, number, team, and points will display in descending order by points. User can select different year to display data in same manner for that year.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="578" alt="Screen Shot 2022-04-20 at 2 49 13 PM" src="https://user-images.githubusercontent.com/99834589/164329112-c54aec2a-ac55-4631-b669-2f5053c23d5d.png">
<img width="820" alt="Screen Shot 2022-04-20 at 2 49 28 PM" src="https://user-images.githubusercontent.com/99834589/164329104-a314cff2-89ef-413b-8d61-ccd1367bb2c8.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a tab 'Driver Standings' identical in size to previous tab
- [x] Listen for a 'click' event on new tab and:
  - [x] Change the clicked tab's background to green and font to white
  - [x] Change the unselected tab's background to red and font to black
  - [x] Send request for driver standings data (position, driver name, race number, team, cumulative points)
  - [x] Display data in a table format
  - [x] Hide table from other tabs
- [x] Confirm that selecting different years changes the data accordingly
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
