### ISSUE TITLE
feature-4-constructor-standings

### ISSUE THREAD

**Issue by Victor-Park** [Victor-Park/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click on "Constructor Standings" tab to see list of constructors and standings

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User now has a 3rd tab option in the nav bar - "Constructor Standings". Clicking on this tab will display data for constructors championship, including name, position, and points for the season. As with other tabs, user can select other years to display data for that given year. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="573" alt="Screen Shot 2022-04-20 at 2 52 11 PM" src="https://user-images.githubusercontent.com/99834589/164329919-122c664e-7c25-4f95-a855-574904b3cb21.png">
<img width="817" alt="Screen Shot 2022-04-20 at 2 52 21 PM" src="https://user-images.githubusercontent.com/99834589/164329911-b9b9430b-ddde-450b-a473-655317c32333.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a tab for "Constructor Standings"
- [x] Listen for the 'click' event and:
  - [x] Change selected tab and non-selected tab's CSS properties appropriately
  - [x] Send request for constructor standings data (position, constructor name, cumulative points)
  - [x] Display data in a table format
  - [x] Hide data tables from non-selected tabs
- [x] Confirm that selecting different year displays data accordingly
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
