### ISSUE TITLE
feature-5-wikipedia-link

### ISSUE THREAD

**Issue by Victor-Park** [Victor-Park/ajax-project#5]
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Listen for 'click' event on driver name, grand prix name, and constructor name and:
  - [ ] Send request to get wikipedia link that matches the name (included in API)
  - [ ] Open up the wikipedia link
 - [ ] Change fonts
 - [ ] Change time displayed to UTC
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
